import styles from '../../styles/AppLayout.module.css'
import React from 'react'
import Head from 'next/head'
import Header from '../containers/header'
import Footer from '../containers/footer'

export default function AppLayout({ children }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>KUBICS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header id='inicio' className={styles.header}>
               <Header />
            </header>
            <main className={styles.main}>
                { children }
            </main>
            <footer id='contacto' className={styles.footer}>
                <Footer/>
            </footer>
        </div>
    )
}
